Some tab cleanup on control script

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -13,17 +13,16 @@ VERTX_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/vertx.pid
 
 # Check if the vertx process is running
 function isrunning() {
-    
-    # Check for running app
-    if [ -f "$VERTX_PID_FILE" ]; then
-      vertxpid=$(cat $VERTX_PID_FILE);
-      if /bin/ps --pid $vertxpid 1>&2 >/dev/null;
-      then
-        return 0
-      fi
+  # Check for running app
+  if [ -f "$VERTX_PID_FILE" ]; then
+    vertxpid=$(cat $VERTX_PID_FILE);
+    if /bin/ps --pid $vertxpid 1>&2 >/dev/null;
+    then
+      return 0
     fi
-   
-    return 1
+  fi
+ 
+  return 1
 }
 
 # Kill the process given by $1 and its children
@@ -105,7 +104,7 @@ function setup_hazelcast {
 }
 
 function start() {
-  echo "Starting Vert.x cartridge"
+  echo "Starting $cartridge_type cart"
 
   if isrunning; then
       echo "Application is already running"
@@ -163,11 +162,9 @@ function start() {
 }
 
 function restart() {
-    echo "Restarting $cartridge_type cart"
-   
-    stop
-    
-    start
+  echo "Restarting $cartridge_type cart"
+  stop
+  start
 }
 
 # Clean up any log files
@@ -180,19 +177,19 @@ function tidy() {
 function threaddump() {
   echo "Thread dump for $cartridge_type cartridge"
 
-    if ! isrunning; then
-        echo "Application is stopped"
-        exit 1
-    elif [ -f "$VERTX_PID_FILE" ]; then
-        pid=$(cat $VERTX_PID_FILE);
-        java_pid=$(ps h --ppid $pid -o '%p')
-        kill -3 $java_pid
-        client_result "Success"
-        client_result ""
-        client_result "The thread dump file will be available via: rhc tail $OPENSHIFT_APP_NAME -g $OPENSHIFT_GEAR_UUID -f ${OPENSHIFT_TMP_DIR}${cartridge_type}.log -o '-n 250'"
-    else 
-        echo "Failed to locate Vert.x PID File"
-    fi
+  if ! isrunning; then
+    echo "Application is stopped"
+    exit 1
+  elif [ -f "$VERTX_PID_FILE" ]; then
+    pid=$(cat $VERTX_PID_FILE);
+    java_pid=$(ps h --ppid $pid -o '%p')
+    kill -3 $java_pid
+    client_result "Success"
+    client_result ""
+    client_result "The thread dump file will be available via: rhc tail $OPENSHIFT_APP_NAME -g $OPENSHIFT_GEAR_UUID -f ${OPENSHIFT_TMP_DIR}${cartridge_type}.log -o '-n 250'"
+  else
+    echo "Failed to locate Vert.x PID File"
+  fi
 }
 
 case "$1" in
